<?php

namespace Database\Seeders;

use App\Models\User;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        DB::table('settings')->insert([
            'name' => 'Transporte Turístico y Empresarial Edwin',
            'rnc' => '131285742',
            'address' => 'KM 17 Marginal de las Américas, Urbanización Prado del Este, Av. Los palmeros #23, SDE',
            'office_phone' => '8094223340',
            'mobile_phone' => '8298866699',
            'mail' => 'info@transporteturisticoedwin.com',
            'website' => 'https://transporteturisticoedwin.com/',
            'facebook' => 'https://www.facebook.com/Transporte-Tur%C3%ADstico-Edwin-SRL-927196780676784',
            'instagram' => 'https://www.instagram.com/transporteturisticoedwin/',
        ]);

        DB::table('users')->insert([
            [
                'name' => 'Erickson Suero',
                'email' => 'ericksuero@gmail.com',
                'password' => Hash::make('superadminpassword'),
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Yoly Mercedes',
                'email' => 'yoly@edwinadmin.com',
                'password' => '$2y$12$bxMD1b2pHTPgwcl6yTaPuulRrbI93F7WcM54hqcFVbH3vvH7.IFTu',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                "name" => "Jorge Popoter ",
                "email" => "jorge@edwinadmin.com",
                'password' => '$2y$12$ontpu.oJ39iZ9AgRFqO1GeZNUnfbQLAVaesPR629LFbPmOORuQbFG',
                'created_at' => now(),
                'updated_at' => now()
            ]
        ]);

        DB::table('service_statuses')->insert([
            ['status' => 'CANCELADO'],
            ['status' => 'COMPLETADO'],
            ['status' => 'EN PROCESO'],
            ['status' => 'PENDIENTE'],
        ]);

        DB::table('service_types')->insert([
            ['type' => 'CORPORATIVO','color' => '#a16207'],
            ['type' => 'ESTANDAR','color' => '#57534e'],
            ['type' => 'VIP','color' => '#ffda83'],
        ]);

        DB::table('service_currencies')->insert([
            ['currency' => 'DOP'],
            ['currency' => 'USD'],
        ]);

        DB::table('drivers')->insert([
            [
                "id" => 1,
                "first_name" => "EDWIN",
                "last_name" => "GERMÁN",
                "email" => null,
                "avatar_url" => null,
                "file" => "F-1",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 2,
                "first_name" => "ANDERSON",
                "last_name" => "APOLINAR GARCIA ",
                "email" => null,
                "avatar_url" => null,
                "file" => "F-80",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
        ]);

        DB::table('companies')->insert([
            [
                "id" => 1,
                "business_name" => "TURINTER ",
                "tradename" => "TURINTER S.A.",
                "logo_url" => null,
                "rnc" => "101096098",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 2,
                "business_name" => "CLIENTE DIRECTO",
                "tradename" => "CLIENTE DIRECTO",
                "logo_url" => null,
                "rnc" => null,
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 5,
                "business_name" => "VIAJES BOHIO",
                "tradename" => "VIAJES BOHIO",
                "logo_url" => null,
                "rnc" => "101147733",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 6,
                "business_name" => "LONGPORT AVIATION SECURITY",
                "tradename" => "LONGPORT AVIATION SECURITY",
                "logo_url" => null,
                "rnc" => "130612196",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 7,
                "business_name" => "ALBA SANCHEZ & ASOCIADOS",
                "tradename" => "ALBA SANCHEZ & ASOCIADOS",
                "logo_url" => null,
                "rnc" => "101132671",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
        ]);

        DB::table('customers')->insert([
            [
                "id" => 1,
                "company_id" => 1,
                "first_name" => "NAYBERT",
                "last_name" => "RAMIREZ",
                "avatar_url" => null,
                "email" => null,
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 2,
                "company_id" => 2,
                "first_name" => "BERRY GRANADOS",
                "last_name" => "OCEAN CONNECTIONS ",
                "avatar_url" => null,
                "email" => null,
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 3,
                "company_id" => 5,
                "first_name" => "FRANK",
                "last_name" => "RUIZ",
                "avatar_url" => null,
                "email" => null,
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 4,
                "company_id" => 5,
                "first_name" => "BONI",
                "last_name" => "CANTO",
                "avatar_url" => null,
                "email" => null,
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 5,
                "company_id" => 6,
                "first_name" => "JANNY PAMELA",
                "last_name" => "DÍAZ",
                "avatar_url" => null,
                "email" => null,
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 6,
                "company_id" => 2,
                "first_name" => "DUPRES",
                "last_name" => "TRAVEL",
                "avatar_url" => null,
                "email" => null,
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 7,
                "company_id" => 7,
                "first_name" => "SELVIA",
                "last_name" => "MATEO",
                "avatar_url" => null,
                "email" => "s.mateo@albasanchez.com",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 8,
                "company_id" => 2,
                "first_name" => "CAROLINA",
                "last_name" => "SILVA",
                "avatar_url" => null,
                "email" => null,
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 9,
                "company_id" => 2,
                "first_name" => "ANA",
                "last_name" => "MONTERO",
                "avatar_url" => null,
                "email" => null,
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
        ]);

        DB::table('destinies')->insert([
            [
                "id" => 1,
                "destiny" => "AILA ",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 2,
                "destiny" => "EXCURSIÓN SAONA ",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 3,
                "destiny" => "CROWNE PLAZA SANTO DOMINGO",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 4,
                "destiny" => "AEROPUERTO PUNTA CANA / PUJ ",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 5,
                "destiny" => "SANTO DOMINGO DIRECCIÓN ",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 6,
                "destiny" => "AEROPUERTO LA ISABELA / JBQ",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 7,
                "destiny" => "AEROPUERTO DE PUERTO PLATA / POP",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 8,
                "destiny" => "AEROPUERTO DE SANTIAGO / STI",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 9,
                "destiny" => "AEROPUERTO LA ROMANA / LRM",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 10,
                "destiny" => "DOMINICAN FIESTA HOTEL SANTO DOMINGO ",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 11,
                "destiny" => "EMBAJADOR HOTEL SANTO DOMINGO",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 12,
                "destiny" => "BARCELO SANTO DOMINGO ",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 13,
                "destiny" => "EXCURSIÓN BUGGIES MACAO / PUNTA CANA",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 14,
                "destiny" => "EXCURSIÓN CATALINA",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 15,
                "destiny" => "DISPOSICIÓN SANTO DOMINGO",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 16,
                "destiny" => "CITY TOUR SANTO DOMINGO / DÍA COMPLETO",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 17,
                "destiny" => "CITY TOUR SANTO DOMINGO / MEDIO DÍA ",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 18,
                "destiny" => "GRAND HOTEL EUROPA / ZONA COLONIAL",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 19,
                "destiny" => "DREAMS ONYX PUNTA CANA / UVERO ALTO",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 20,
                "destiny" => "CITY TOUR PUERTO PLATA ",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 21,
                "destiny" => "EXCURSIÓN SENDERO DEL CACAO",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 22,
                "destiny" => "GRAND SIRENIS PUNTA CANA / UVERO ALTO",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 23,
                "destiny" => "HODELPA NOVUS PLAZA / ZONA COLONIAL",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 24,
                "destiny" => "HODELPA NICOLÁS DE OVANDO / ZONA COLONIAL",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 25,
                "destiny" => "HODELPA CARIBE COLONIAL / ZONA COLONIAL",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 26,
                "destiny" => "HYATT CENTRIC CHURCILL / SANTO DOMINGO ",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 27,
                "destiny" => "CENTRAL SUITES / SANTO DOMINGO ",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 28,
                "destiny" => "RAMADA PRINCESS HOTEL / SANTO DOMINGO ",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 29,
                "destiny" => "SHERATON SANTO DOMINGO",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 30,
                "destiny" => "RENAISSANCE JARAGUA SANTO DOMINGO",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 31,
                "destiny" => "CRUCE LAS MERCEDES / CRUCE SANTANA",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 32,
                "destiny" => "PARQUE DE YAGUATE / SAN CRISTOBAL",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 33,
                "destiny" => "ITABO / IDA Y VUELTA",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 34,
                "destiny" => "CRUCE LAS MERCEDES / YAGUATE",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 35,
                "destiny" => "NAVARRETE",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 36,
                "destiny" => "CRUCE DE VILLA MELLA",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 37,
                "destiny" => "EL SEIBO / LA CUCHILLA",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 38,
                "destiny" => "PUNTA CANA / ZONA FRANCA",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 39,
                "destiny" => "HARD ROCK PUNTA CANA",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 40,
                "destiny" => "SUNSCAPE COCO PUNTA CANA",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 41,
                "destiny" => "SANTIAGO DIRECCIÓN",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 42,
                "destiny" => "VIVA V SAMANA / LAS TERRENAS",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 43,
                "destiny" => "VIVA V HEAVENS / PUERTO PLATA",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 44,
                "destiny" => "VIVA TANGERINE / CABARETE",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 45,
                "destiny" => "EMOTIONS BY HODELPA / PUERTO PLATA",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 46,
                "destiny" => "EMOTIONS BY HODELPA / JUAN DOLIO",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 47,
                "destiny" => "CORAL COSTA CARIBE / JUAN DOLIO",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 48,
                "destiny" => "CATALONIA SANTO DOMINGO",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 49,
                "destiny" => "GRAND BAVARO PRINCESS / PUNTA CANA",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 50,
                "destiny" => "SANTO DOMINGO ESTE",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 51,
                "destiny" => "SANTO DOMINGO NORTE",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 52,
                "destiny" => "AUTOPISTA DUARTE ",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 53,
                "destiny" => "EXCURSIÓN CUEVA DE LAS MARAVILLAS",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 54,
                "destiny" => "EXCURSIÓN ALTOS DE CHAVÓN ",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 55,
                "destiny" => "CAYO LEVANTADO SAMANÁ / IDA Y VUELTA",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 56,
                "destiny" => "HAINA / NODO",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 57,
                "destiny" => "SAN CRISTOBAL / YAGUATE ",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 58,
                "destiny" => "SALTO ALTO BAYAGUANA / IDA Y VUELTA",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 59,
                "destiny" => "WHALA BOCA CHICA",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 60,
                "destiny" => "WHALA BAVARO",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 61,
                "destiny" => "WHALA BAYAHIBE",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 62,
                "destiny" => "PUNTA CANA DIRECCIÓN",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 63,
                "destiny" => "TROPICAL DELUXE PRINCESS / PUNTA CANA",
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
        ]);
    }
}
